### ISSUE TITLE
disable homescreen rotation

### ISSUE THREAD

**Issue by KhafraDev** [castyte/osssettings#5]
**What category does the feature fit into?**
Springboard

**Describe the solution you'd like**
disable homescreen rotation on + sized devices but not in apps

**Describe alternatives you've considered**
Notate (disables in apps) and Nuus (doesn't work)

**Additional context**
N/A

**Comment by castyte** [comment]
This will be added for the next release, thanks for submitting!

**Comment by castyte** [comment]
This was just added in[ prerelease-1](https://github.com/castyte/osssettings/releases/tag/prerelease-1)!
