### ISSUE TITLE
Move dock location 

### ISSUE THREAD

**Issue by Caeg** [castyte/osssettings#6]
**What category does the feature fit into?**
Springboard 

**Describe the solution you'd like**
The ability to move be dock up or down. I personally want my dock lower on my phone. 

**Describe alternatives you've considered**
There use to be a tweak called quayshift that did this but it isn’t supported for iOS 12

**Additional context**
I’ll donate $5 if you add this feature. :(

**Comment by castyte** [comment]
This is likely too big of a feature too add, however I may make a stand-alone tweak for this in the future. Thanks for submitting!
