### ISSUE TITLE
Custom folder background while opened and icon

### ISSUE THREAD

**Issue by joek1ng4312** [castyte/osssettings#7]
**What category does the feature fit into?**
Springboard/Folders? 

**Describe the solution you'd like**
It would be cool to add the option to hide folder background while in the folder and another to hide the ugly background behind the icon on springboard. Some other tweaks have these features but it would be easier on my device to have these in just 1 tweak. 

**Describe alternatives you've considered**

**Additional context**

**Comment by castyte** [comment]
Hi, could you possibly share the tweaks that already do this?

**Comment by joek1ng4312** [comment]
Hello, the current tweaks I have that to implement these are essentials and springtomize 4 but springtomize fails to hide the icon background blur for me. A free alternative is XenHTML which successfully works (sometimes) but doesn’t provide the option to disable in-folder blur, only icon blur.
Thanks


On 24/06/2019, at 12:31 AM, castyte <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, could you possibly share the tweaks that already do this?

**Comment by joek1ng4312** [comment]
Hi, sorry I forgot to mention another free alternative called folderbackgroundbegone which hides the folder icon background. I’m not to sure if it’s available via repo but here’s the reddit post https://www.google.com/amp/s/amp.reddit.com/r/jailbreak/comments/7squ7a/release_folderbackgroundbegone_remove_folder/



On 24/06/2019, at 12:31 AM, castyte <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, could you possibly share the tweaks that already do this?

**Comment by castyte** [comment]
Thanks, I have finished the hide background while opened part and I will do the icon soon.  
If you are on A11 or earlier you can download and test it [here](https://github.com/castyte/osssettings/releases/tag/prerelease-3)

**Comment by joek1ng4312** [comment]
Seems to work fine thanks bud



On 24/06/2019, at 5:10 AM, castyte <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #7<https://github.com/castyte/osssettings/issues/7>.
