### ISSUE TITLE
Change icon dock size and icon size in springboard

### ISSUE THREAD

**Issue by btninja** [castyte/osssettings#8]
**What category does the feature fit into?**
[Springboard]

**Describe the solution you'd like**
Ability to change the size of the icons in dock and springboard. Preferably by percentage like Springtomize.

**Describe alternatives you've considered**
Is pretty straightforward.

**Additional context**
None.

**Comment by castyte** [comment]
This could possibly be implemented in the future, however at the moment that may be too big. I believe @Nepeta recently released cuboid for free that can change icon size.
